# -*- coding: utf-8 -*-
"""Breast_cancer_Naive_Day02.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16Ubg2eOQg-Wnbl9lE4d412pXutZdRWEN
"""

pip install scikit-learn

import sklearn
from sklearn.datasets import load_breast_cancer

data = load_breast_cancer()

# Get the names of the target labels (e.g., 'malignant' and 'benign')
label_names = data['target_names']

# Get the actual target values (0 for malignant, 1 for benign)
labels = data['target']

# Get the feature names (e.g., mean radius, mean texture, etc.)
feature_names = data['feature_names']

# Get the actual data (numerical values of all features for each sample)
features = data['data']

print(label_names)
print(labels[0])
print(feature_names)
print(features[0])

# importing the function
from sklearn.model_selection import train_test_split

# splitting the data
train, test, train_labels, test_labels = train_test_split(features, labels,
                                       test_size = 0.33, random_state = 42)

from sklearn.naive_bayes import GaussianNB

gnb = GaussianNB()

model = gnb.fit(train, train_labels)

predictions = gnb.predict(test)
print(predictions)

# importing the accuracy measuring function
from sklearn.metrics import accuracy_score

# evaluating the accuracy
print(accuracy_score(test_labels, predictions))